name = "NumericalTypeAliases"
uuid = "be9b823e-291e-41a1-b8ce-806204e78f92"
authors = ["Sasha Petrenko <sap625@umsystem.edu>"]
version = "0.2.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
DocStringExtensions = "0.8, 0.9"
julia = "1"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "Logging"]
